export default {
  collectCoverageFrom: ['!src/**/*.d.ts', 'src/**/*.{js,jsx,ts,tsx}'],
  moduleFileExtensions: [
    'js',
    'json',
    'jsx',
    'node',
    'ts',
    'tsx',
    'web.js',
    'web.jsx',
    'web.ts',
    'web.tsx',
  ],
  moduleNameMapper: {
    '^.+\\.module\\.(le|sa|sc|c)ss$': 'identity-obj-proxy',
    '^Assets(.*)$': '<rootDir>/src/assets/$1',
    '^Components(.*)$': '<rootDir>/src/components/$1',
    '^Features(.*)$': '<rootDir>/src/features/$1',
    '^Pages(.*)$': '<rootDir>/src/pages/$1',
    '^react-native$': 'react-native-web',
    '^Resources(.*)$': '<rootDir>/src/resources/$1',
    '^Services(.*)$': '<rootDir>/src/services/$1',
  },
  modulePaths: ['.', 'node_modules', 'src'],
  roots: ['<rootDir>/src'],
  setupFiles: ['react-app-polyfill/jsdom'],
  setupFilesAfterEnv: ['<rootDir>/src/resources/setup/tests.ts'],
  testEnvironment: 'jest-environment-jsdom-fourteen',
  testMatch: ['<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}'],
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': '<rootDir>/node_modules/babel-jest',
    '^.+\\.css$': '<rootDir>/config/jest/cssTransform.js',
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '<rootDir>/config/jest/fileTransform.js',
  },
  transformIgnorePatterns: [
    '[/\\\\]node_modules[/\\\\].+\\.((t|j)sx?)$',
    '^.+\\.module\\.(le|sa|sc|c)ss$',
  ],
  watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
};
